version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run:
          start-command: "cd api && npm install && cd ../client && npm install && cd .. && npm run start"

