version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          start: cd client && npm install && npm start
          wait-on: http://localhost:3000
          command: npx cypress run --headless