# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  cypress-suite:
    docker:
      - image: cypress/browsers
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "remove deps"
          command: "rm -rf node_modules && rm -rf package-lock.json"
      - run:
          name: "install deps"
          command: "npm install && cd client && npm install && cd ../api && npm install" 
      - run:
          name: Build React App
          command: npm run build
      # Serve the built React app
      - run:
          name: Serve React App
          command: npx serve -s build -l 3000
      - run:
          name: "try to run cypress tests"
          command: "npx cypress run --browser chrome"
          environment: 

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  cypress-tests:
    jobs:
      - cypress-suite
