# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  cypress: cypress-io/cypress@3
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  cypress-tests:
    jobs:
      - cypress/run # "run" job comes from "cypress" orb
          start-command: 'npm run start'
