version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  cypress_e2e:
    jobs:
      - cypress/run:
          install-browsers: true
          cypress-command: 'npx wait-on@latest http://localhost:3000 && npx cypress run --browser chrome'
          start-command: 'cd client && npm install && npm run start'